import collections
import pathlib
import textwrap

import exifread

samples_directory = pathlib.Path('samples')

image_paths = list()
image_paths.extend(samples_directory.glob('sample-sites/*.jpg'))
image_paths.extend(samples_directory.glob('plates/*.jpg'))

sample_to_snippets = collections.OrderedDict()
for path in image_paths:
    sample_id, _ = path.stem.split('-', 1)
    with path.open('rb') as read_file:
        tags = exifread.process_file(read_file, details=False)
    gps_coords = exifread.utils.get_gps_coords(tags)
    snippet = textwrap.dedent(f'''\

    ## {path.stem}

    + EXIF DateTimeOriginal: {tags.get('EXIF DateTimeOriginal')}
    + Geolocation: {gps_coords}

    ![{path.stem}]({path.relative_to(samples_directory)})
    ''')
    snippets = sample_to_snippets.setdefault(sample_id, [])
    snippets.append(snippet)


for sample_id, snippets in sample_to_snippets.items():
    markdown = f'# Autogenerated details for {sample_id}\n'
    markdown += ''.join(snippets)
    path = samples_directory.joinpath(f'{sample_id}-details.md')
    with path.open('wt') as write_file:
        write_file.write(markdown)
